(ns monster.dict)

; source https://lt.wikipedia.org/wiki/2016%E2%80%932020_m._Seimas
(def mps
  [{:text "Agnė Bilotaitė"}
   {:text "Agnė Širinskienė"}
   {:text "Alfredas Stasys Nausėda"}
   {:text "Algimantas Dumbrava"}
   {:text "Algimantas Kirkutis"}
   {:text "Algimantas Salamakinas"}
   {:text "Algirdas Butkevičius"}
   {:text "Algirdas Sysas"}
   {:text "Algis Strelčiūnas"}
   {:text "Andriejus Stančikas"}
   {:text "Andrius Kubilius"}
   {:text "Andrius Palionis"}
   {:text "Antanas Matulas"}
   {:text "Antanas Vinkus"}
   {:text "Artūras Skardžius"}
   {:text "Arvydas Anušauskas"}
   {:text "Arvydas Nekrošius"}
   {:text "Arūnas Gelūnas"}
   {:text "Arūnas Gumuliauskas"}
   {:text "Asta Kubilienė"}
   {:text "Audronius Ažubalis"}
   {:text "Audrys Šimas"}
   {:text "Aurelijus Veryga"}
   {:text "Aurimas Gaidžiūnas"}
   {:text "Aušra Maldeikienė"}
   {:text "Aušra Papirtienė"}
   {:text "Aušrinė Armonaitė"}
   {:text "Aušrinė Norkienė"}
   {:text "Bronislovas Matelis"}
   {:text "Bronius Markauskas"}
   {:text "Dainius Gaižauskas"}
   {:text "Dainius Kepenis"}
   {:text "Dainius Kreivys"}
   {:text "Darius Kaminskas"}
   {:text "Dovilė Šakalienė"}
   {:text "Edmundas Pupinis"}
   {:text "Egidijus Vareikis"}
   {:text "Emanuelis Zingeris"}
   {:text "Eugenijus Gentvilas"}
   {:text "Eugenijus Jovaiša"}
   {:text "Gabrielius Landsbergis"}
   {:text "Gediminas Kirkilas"}
   {:text "Gediminas Vasiliauskas"}
   {:text "Gintaras Steponavičius"}
   {:text "Gintaras Vaičekauskas"}
   {:text "Gintarė Skaistė"}
   {:text "Gintautas Kindurys"}
   {:text "Greta Kildišienė"}
   {:text "Guoda Burokienė"}
   {:text "Ingrida Šimonytė"}
   {:text "Irena Degutienė"}
   {:text "Irena Šiaulienė"}
   {:text "Irina Rozova"}
   {:text "Jaroslav Narkevič"}
   {:text "Jonas Jarutis"}
   {:text "Jonas Liesys"}
   {:text "Jonas Varkalys"}
   {:text "Julius Sabatauskas"}
   {:text "Juozas Baublys"}
   {:text "Juozas Bernatonis"}
   {:text "Juozas Imbrasas"}
   {:text "Juozas Olekas"}
   {:text "Juozas Rimkus"}
   {:text "Juozas Varžgalys"}
   {:text "Jurgis Razma"}
   {:text "Justas Džiugelis"}
   {:text "Kazys Starkevičius"}
   {:text "Kęstutis Bacvinka"}
   {:text "Kęstutis Bartkevičius"}
   {:text "Kęstutis Glaveckas"}
   {:text "Kęstutis Masiulis"}
   {:text "Kęstutis Mažeika"}
   {:text "Kęstutis Pūkas"}
   {:text "Kęstutis Smirnovas"}
   {:text "Laimutė Matkevičienė"}
   {:text "Lauras Stacevičius"}
   {:text "Laurynas Kasčiūnas"}
   {:text "Leonard Talmont"}
   {:text "Levutė Staniuvienė"}
   {:text "Linas Antanas Linkevičius"}
   {:text "Linas Balsys"}
   {:text "Mantas Adomėnas"}
   {:text "Michal Mackevič"}
   {:text "Mindaugas Bastys"}
   {:text "Mindaugas Puidokas"}
   {:text "Monika Navickienė"}
   {:text "Mykolas Majauskas"}
   {:text "Naglis Puteikis"}
   {:text "Paulius Saudargas"}
   {:text "Petras Gražulis"}
   {:text "Petras Nevulis"}
   {:text "Petras Valiūnas"}
   {:text "Petras Čimbaras"}
   {:text "Povilas Urbšys"}
   {:text "Radvilė Morkūnaitė-Mikulėnienė"}
   {:text "Raimundas Martinėlis"}
   {:text "Raminta Popovienė"}
   {:text "Ramūnas Karbauskis"}
   {:text "Rasa Budbergytė"}
   {:text "Rasa Juknevičienė"}
   {:text "Remigijus Žemaitaitis"}
   {:text "Rima Baškienė"}
   {:text "Rimantas Jonas Dagys"}
   {:text "Rimantas Sinkevičius"}
   {:text "Rimantė Šalaševičiūtė"}
   {:text "Rimas Andrikis"}
   {:text "Rita Tamašunienė"}
   {:text "Ričardas Juška"}
   {:text "Robertas Šarknickas"}
   {:text "Rokas Žilinskas"}
   {:text "Rūta Miliūtė"}
   {:text "Saulius Skvernelis"}
   {:text "Sergejus Jovaiša"}
   {:text "Simonas Gentvilas"}
   {:text "Stasys Jakeliūnas"}
   {:text "Stasys Tumėnas"}
   {:text "Stasys Šedbaras"}
   {:text "Tadas Langaitis"}
   {:text "Tomas Tomilinas"}
   {:text "Valentinas Bukauskas"}
   {:text "Valerijus Simulik"}
   {:text "Valius Ąžuolas"}
   {:text "Vanda Kravčionok"}
   {:text "Vida Ačienė"}
   {:text "Viktoras Pranckietis"}
   {:text "Viktoras Rinkevičius"}
   {:text "Viktorija Čmilytė-Nielsen"}
   {:text "Virgilijus Alekna"}
   {:text "Virgilijus Poderys"}
   {:text "Virginija Vingrienė"}
   {:text "Virginijus Sinkevičius"}
   {:text "Vitalijus Gailius"}
   {:text "Vytautas Bakas"}
   {:text "Vytautas Juozapaitis"}
   {:text "Vytautas Kamblevičius"}
   {:text "Vytautas Kernagis"}
   {:text "Vytautas Rastenis"}
   {:text "Zbignev Jedinskij"}
   {:text "Zenonas Streikus"}
   {:text "Česlav Olševski"}
   {:text "Žygimantas Pavilionis"}])
